version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - kafka
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
